apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: nginx-pipeline
description: Pipeline for Nginx app
serialPipeline:
  stages:
  - targetId: gke-prod
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: gke-prod
description: GKE Autopilot production cluster
gke:
  cluster: projects/gcp-portability/locations/us-central1/clusters/autopilot-cluster-1